### ISSUE TITLE
No text displayed in the lower left corner of search results

### ISSUE THREAD

**Issue by wenLiangcan** [zealdocs/zeal#540]
The executable is built from commit ecb5e3d

![zeal_005](https://cloud.githubusercontent.com/assets/1244181/14710921/f2ae8ce2-0809-11e6-975f-ab168d19ae40.png)

**Comment by trollixx** [comment]
I can't reproduce this. Does the problem go away if you build earlier commits?

**Comment by wenLiangcan** [comment]
Commit 5431550 has no such problem (Zeal version of this commit is 0.2.0)

**Comment by trollixx** [comment]
That's a pretty big diff. Could you try [`git bisect`](https://git-scm.com/docs/git-bisect)?

**Comment by wenLiangcan** [comment]
The last commit without this problem is 851fccb, but that area is completely disappeared in its successor 522e514.

**Comment by trollixx** [comment]
Thanks for checking this out. The problem is with broken settings. Deleting `splitter_geometry` and `sections_geometry` options from Zeal's configuration file should fix the problem. With the next upgrade these options will be reset automatically, but there's no way to do that for a version built from the current source.

**Comment by trollixx** [comment]
Alternatively, something wrong could be with the text rendering. Unfortunately, I can't reproduce this issue. Does it still occur for you?

**Comment by wenLiangcan** [comment]
After modifying the configuration file the issue still exists.

**Comment by trollixx** [comment]
I don't see anything in 522e514, that would cause such a problem. No changes to the delegate that actually renders the text for every item. @drognanar any ideas?

**Comment by trollixx** [comment]
@wenLiangcan, @wicast I've just committed a fix, the problem should no longer occur for you.
